In [2]:
import pandas as pd
import numpy as np

# Load Data

In [3]:
df = pd.read_csv("../../raw_data/NFL/NFL_scrapped.csv")
df.head()

,W,L,T,PCT,HOME,AWAY,DIV,CONF,PF,PA,DIFF,STRK,Team,Year
0,14,2,0,0.875,8-0,6-2,5-1,11-1,348,238,110,W12,* -- NE New England Patriots,2003
1,13,3,0,0.813,8-0,5-3,5-1,10-2,484,332,152,W1,z -- KC Kansas City Chiefs,2003
2,12,4,0,0.750,5-3,7-1,5-1,9-3,447,336,111,W1,z -- IND Indianapolis Colts,2003
3,12,4,0,0.750,8-0,4-4,4-2,8-4,447,328,119,L1,z -- STL St. Louis Rams,2003
4,12,4,0,0.750,7-1,5-3,4-2,8-4,435,324,111,W3,y -- TEN Tennessee Titans,2003

## Format of the data:

- Wins, Losses and Ties per Team per Season from 2000 to 2021
- We only need Year, NFL Team, W, L, T columns

## Preprocessing

In [7]:
df

,W,L,T,PCT,HOME,AWAY,DIV,CONF,PF,PA,DIFF,STRK,Team,Year
0,14,2,0,0.875,8-0,6-2,5-1,11-1,348,238,110,W12,* -- NE New England Patriots,2003
1,13,3,0,0.813,8-0,5-3,5-1,10-2,484,332,152,W1,z -- KC Kansas City Chiefs,2003
2,12,4,0,0.750,5-3,7-1,5-1,9-3,447,336,111,W1,z -- IND Indianapolis Colts,2003
3,12,4,0,0.750,8-0,4-4,4-2,8-4,447,328,119,L1,z -- STL St. Louis Rams,2003
4,12,4,0,0.750,7-1,5-3,4-2,8-4,435,324,111,W3,y -- TEN Tennessee Titans,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603,4,13,0,0.235,3-6,1-7,0-6,4-8,310,504,-194,L2,e -- NYJ New York Jets,2021
604,4,13,0,0.235,3-5,1-8,1-5,3-9,258,416,-158,L6,e -- NYG New York Giants,2021
605,4,13,0,0.235,2-7,2-6,3-3,4-8,280,452,-172,L2,e -- HOU Houston Texans,2021
606,3,13,1,0.206,3-5,0-8-1,2-4,3-9,325,467,-142,W1,e -- DET Detroit Lions,2021
607,3,14,0,0.176,3-6,0-8,1-5,3-9,253,457,-204,W1,e -- JAX Jacksonville Jaguars,2021

## Create new dataframe with desired output

In [5]:
df_nfl_data = pd.DataFrame(
    columns=["Year", "Teams", "Wins", "Losses", "Ties", "#Games"]
)

In [8]:
grouped = df.groupby("Year")

for name, group in grouped:
    teams = group["Team"].tolist()
    wins = group["W"].tolist()
    losses = group["L"].tolist()
    ties = group["T"].tolist()

    ngames = wins[0] + losses[0] + ties[0]
    # concat to the dataframe

    df_tmp = (
        pd.Series(
            {
                "Year": name,
                "Teams": teams,
                "Wins": wins,
                "Losses": losses,
                "Ties": ties,
                "#Games": ngames,
            }
        )
        .to_frame()
        .T
    )
    df_nfl_data = pd.concat([df_nfl_data, df_tmp])

In [10]:
# Save the data
df_nfl_data.to_parquet("../../prepared_data/NFL_data.parquet", index=False)